### ISSUE TITLE
Line from startNode broken in the mouse:up part 

### ISSUE THREAD

**Issue by LauraneS** [LauraneS/audio-beads-project#27]

**Comment by LauraneS** [comment]
Didn't change anything to the code, tried debugging and all of a sudden it worked fine.
Weird. Hopefully it doesn't break randomly again...

**Comment by alistairstead3408** [comment]
Looks like this is still an issue - I pulled and couldn't get a sleep node to connect to a play node. The error was:

`Uncaught TypeError: Cannot read property 'set' of undefined`
